import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#f5f1e8] py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <Link href="/onboarding">
          <Button variant="ghost" className="mb-8 text-[#059669] hover:text-[#047857]">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Onboarding
          </Button>
        </Link>

        <h1 className="text-4xl font-bold text-[#2d5016] mb-8">Terms of Service</h1>
        
        <div className="prose prose-lg max-w-none text-[#374151] space-y-6">
          <p className="text-[#6b7280]">
            Last updated: {new Date().toLocaleDateString()}
          </p>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Spill the Vibes ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">2. Description of Service</h2>
            <p>
              Spill the Vibes is an AI-powered platform that provides:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Personalized relationship advice and insights</li>
              <li>Mood-based conversation experiences</li>
              <li>AI-generated responses to your questions and situations</li>
              <li>A safe space to explore relationship dynamics</li>
            </ul>
            <p className="mt-4">
              <strong>Important:</strong> Our Service provides AI-generated advice for informational and entertainment purposes only. It is not a substitute for professional counseling, therapy, or medical advice.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">3. User Eligibility</h2>
            <p>To use our Service, you must:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Be at least 13 years old</li>
              <li>Have the legal capacity to enter into this agreement</li>
              <li>Provide accurate age information during registration</li>
              <li>Use the Service in compliance with all applicable laws</li>
            </ul>
            <p className="mt-4">
              Users under 18 will receive age-appropriate content and additional safety measures.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">4. User Responsibilities</h2>
            <p>When using our Service, you agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide honest and accurate information</li>
              <li>Maintain the confidentiality of your account</li>
              <li>Use the Service respectfully and responsibly</li>
              <li>Not share harmful, illegal, or inappropriate content</li>
              <li>Not attempt to manipulate or abuse the AI system</li>
              <li>Respect the privacy and rights of others</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">5. Content Guidelines</h2>
            <h3 className="text-xl font-medium text-[#374151]">Prohibited Content</h3>
            <p>You may not submit content that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Is harmful, threatening, or harassing</li>
              <li>Contains explicit sexual content</li>
              <li>Promotes violence or illegal activities</li>
              <li>Violates someone's privacy or rights</li>
              <li>Contains false or misleading information</li>
              <li>Attempts to identify specific individuals</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">6. AI-Generated Content</h2>
            <p>
              You understand and acknowledge that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Responses are generated by AI and may not always be accurate</li>
              <li>AI advice should not replace professional help</li>
              <li>We do not guarantee specific outcomes from following AI suggestions</li>
              <li>The AI may occasionally produce unexpected or inappropriate responses</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">7. Intellectual Property</h2>
            <p>
              All content on our platform, including but not limited to text, graphics, logos, and software, is the property of Spill the Vibes or its licensors and is protected by intellectual property laws.
            </p>
            <p className="mt-4">
              You retain ownership of the content you submit, but grant us a license to use it for providing and improving our Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">8. Privacy and Data Use</h2>
            <p>
              Your use of our Service is also governed by our Privacy Policy. By using the Service, you consent to our collection and use of data as described in the Privacy Policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">9. Disclaimers and Limitations</h2>
            <h3 className="text-xl font-medium text-[#374151]">No Professional Advice</h3>
            <p>
              Our Service does not provide medical, legal, financial, or professional therapeutic advice. Always consult qualified professionals for serious matters.
            </p>
            
            <h3 className="text-xl font-medium text-[#374151]">Service Availability</h3>
            <p>
              We strive to maintain Service availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable for maintenance or updates.
            </p>

            <h3 className="text-xl font-medium text-[#374151]">Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by law, Spill the Vibes shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">10. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Service at any time for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violation of these Terms</li>
              <li>Harmful or inappropriate behavior</li>
              <li>At our sole discretion with or without notice</li>
            </ul>
            <p className="mt-4">
              You may terminate your use of the Service at any time by discontinuing access.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">11. Modifications to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of material changes through the Service or via email. Your continued use of the Service after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">13. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us at:
            </p>
            <div className="bg-white p-4 rounded-lg border border-[#e5e7eb]">
              <p>Email: legal@spillthevibes.com</p>
              <p>Address: [Your Company Address]</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#2d5016]">14. Entire Agreement</h2>
            <p>
              These Terms constitute the entire agreement between you and Spill the Vibes regarding the use of the Service and supersede any prior agreements.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[#e5e7eb]">
          <Link href="/onboarding">
            <Button className="bg-[#059669] hover:bg-[#047857] text-white">
              Return to Onboarding
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}